server:
  port: 8080



spring:
  servlet:
    multipart:
      enabled: false        # ← ADD THIS — stops gateway from consuming multipart


  application:
    name: api-gateway

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: oauth2-route
              uri: http://localhost:8081
              predicates:
                - Path=/oauth2/**

            - id: login-route
              uri: http://localhost:8081
              predicates:
                - Path=/login/**

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/profile/**

            - id: user-uploads
              uri: http://localhost:8082
              predicates:
                - Path=/uploads/**

            - id: resume-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/resumes/**

            - id: job-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/jobs/**,/api/applications/**

