# Override Eureka to Docker hostname
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

# Override Feign client URL for Docker networking
user-service:
  url: http://user-service:8082
