/**
 * Generates a print-friendly PDF of the ATS results by injecting
 * a hidden iframe styled for A4 print, then triggering window.print().
 * No third-party dependencies required.
 */
import type { ResumeScoreResponse } from '../types/index';

const SCORE_COLOR = (v: number) =>
  v >= 75 ? '#16a34a' : v >= 50 ? '#d97706' : '#dc2626';

const bar = (label: string, value: number) => `
  <div style="margin-bottom:12px;">
    <div style="display:flex;justify-content:space-between;margin-bottom:4px;">
      <span style="font-size:13px;">${label}</span>
      <strong style="font-size:13px;color:${SCORE_COLOR(value)}">${value}%</strong>
    </div>
    <div style="background:#e5e7eb;border-radius:4px;height:8px;overflow:hidden;">
      <div style="height:8px;width:${value}%;background:${SCORE_COLOR(value)};border-radius:4px;"></div>
    </div>
  </div>`;

const chips = (items: string[], color: string) =>
  items
    .map(
      (s) =>
        `<span style="display:inline-block;margin:3px;padding:3px 10px;border-radius:999px;
          border:1px solid ${color};color:${color};font-size:12px;">${s}</span>`
    )
    .join('');

const listItems = (items: string[]) =>
  items.map((s) => `<li style="margin-bottom:4px;font-size:13px;">• ${s}</li>`).join('');

const RECOMMENDATION_COLOR: Record<string, string> = {
  'Excellent Match': '#16a34a',
  'Good Match': '#2563eb',
  'Moderate Match': '#d97706',
  'Poor Match': '#dc2626',
};

export function downloadAtsResultAsPdf(
  result: ResumeScoreResponse,
  resumeFileName?: string
): void {
  const recColor = RECOMMENDATION_COLOR[result.recommendation] ?? '#374151';
  const now = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>ATS Score Report – HirePilot</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      background: #fff;
      color: #111827;
      padding: 40px 48px;
    }
    h1 { font-size: 22px; font-weight: 700; color: #1e293b; }
    h2 { font-size: 15px; font-weight: 600; margin: 24px 0 10px; color: #374151; }
    .meta { font-size: 12px; color: #6b7280; margin-top: 4px; }
    .badge {
      display: inline-block; margin-top: 8px; padding: 4px 14px;
      border-radius: 999px; font-size: 13px; font-weight: 700;
      background: ${recColor}20; color: ${recColor};
      border: 1.5px solid ${recColor};
    }
    .gauge {
      width: 120px; height: 120px; border-radius: 50%;
      border: 6px solid ${SCORE_COLOR(result.overallScore)};
      display: flex; flex-direction: column; align-items: center;
      justify-content: center; margin: 16px auto;
    }
    .gauge-score { font-size: 36px; font-weight: 800; color: ${SCORE_COLOR(result.overallScore)}; }
    .gauge-label { font-size: 11px; color: #6b7280; }
    .divider { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
    ul { list-style: none; padding-left: 0; }
    .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; }
    @media print {
      body { padding: 24px 32px; }
    }
  </style>
</head>
<body>
  <h1>ATS Score Report</h1>
  <p class="meta">
    Generated by HirePilot &nbsp;|&nbsp; ${now}
    ${resumeFileName ? `&nbsp;|&nbsp; Resume: <strong>${resumeFileName}</strong>` : ''}
  </p>
  <div class="badge">${result.recommendation}</div>

  <hr class="divider" />

  <div class="gauge">
    <span class="gauge-score">${result.overallScore}</span>
    <span class="gauge-label">ATS Score</span>
  </div>

  <hr class="divider" />
  <h2>Score Breakdown</h2>
  ${bar('Skills Match', result.skillsMatch)}
  ${bar('Experience Match', result.experienceMatch)}
  ${bar('Education Match', result.educationMatch)}

  ${
    result.strengths.length
      ? `<hr class="divider" />
         <h2>Strengths</h2>
         <div>${chips(result.strengths, '#16a34a')}</div>`
      : ''
  }

  ${
    result.missingSkills.length
      ? `<hr class="divider" />
         <h2>Missing Skills</h2>
         <div>${chips(result.missingSkills, '#dc2626')}</div>`
      : ''
  }

  ${
    result.suggestions.length
      ? `<hr class="divider" />
         <h2>Suggestions</h2>
         <ul>${listItems(result.suggestions)}</ul>`
      : ''
  }

  <p class="footer">HirePilot · ATS Resume Analyzer · Report generated on ${now}</p>
</body>
</html>`;

  // Create a hidden iframe, write the HTML into it, then print it
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.top = '-9999px';
  iframe.style.left = '-9999px';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = 'none';
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) {
    document.body.removeChild(iframe);
    return;
  }

  doc.open();
  doc.write(html);
  doc.close();

  // Wait for iframe to load before printing
  iframe.onload = () => {
    try {
      iframe.contentWindow?.print();
    } finally {
      // Remove after a short delay to let print dialog open
      setTimeout(() => {
        document.body.removeChild(iframe);
      }, 1000);
    }
  };

  // Fallback: if onload doesn't fire, try after short timeout
  setTimeout(() => {
    if (document.body.contains(iframe)) {
      try {
        iframe.contentWindow?.print();
      } finally {
        setTimeout(() => {
          if (document.body.contains(iframe)) {
            document.body.removeChild(iframe);
          }
        }, 1000);
      }
    }
  }, 600);
}
